name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install Flask Flask-Frozen

      - name: Generate static files
        run: |
          export FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}
          python freeze.py
        if: ${{ success() }}

      - name: Deploy to Github Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.REACT_COMM_APP }}
          publis_dir: ./build
          commit_message: "Auto Deploy"
